### ISSUE TITLE
Can't find Dockerfile

### ISSUE THREAD

**Issue by ADKosm** [chintak/theano-lasagne-docker#1]
It is a very interestring project, but unfortunatly, I can't find Dockerfile. :cry:

**Comment by chintak** [comment]
Look at the branches - `gpu`, `cpu` and `cpu-no-theano`. They contain the Dockerfile and additional relevant files.

https://github.com/chintak/theano-lasagne-docker/tree/gpu
https://github.com/chintak/theano-lasagne-docker/tree/cpu
https://github.com/chintak/theano-lasagne-docker/tree/cpu-no-theano
